// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	model "github.com/JieeiroSst/itjob/model"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CheckAccount mocks base method.
func (m *MockUserRepository) CheckAccount(user model.Users) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccount", user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckAccount indicates an expected call of CheckAccount.
func (mr *MockUserRepositoryMockRecorder) CheckAccount(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccount", reflect.TypeOf((*MockUserRepository)(nil).CheckAccount), user)
}

// CheckAccountExists mocks base method.
func (m *MockUserRepository) CheckAccountExists(user model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccountExists", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAccountExists indicates an expected call of CheckAccountExists.
func (mr *MockUserRepositoryMockRecorder) CheckAccountExists(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccountExists", reflect.TypeOf((*MockUserRepository)(nil).CheckAccountExists), user)
}

// CheckEmail mocks base method.
func (m *MockUserRepository) CheckEmail(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmail", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckEmail indicates an expected call of CheckEmail.
func (mr *MockUserRepositoryMockRecorder) CheckEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmail", reflect.TypeOf((*MockUserRepository)(nil).CheckEmail), email)
}

// CheckIP mocks base method.
func (m *MockUserRepository) CheckIP(ip string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIP", ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckIP indicates an expected call of CheckIP.
func (mr *MockUserRepositoryMockRecorder) CheckIP(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIP", reflect.TypeOf((*MockUserRepository)(nil).CheckIP), ip)
}

// CheckPassword mocks base method.
func (m *MockUserRepository) CheckPassword(password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPassword", password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckPassword indicates an expected call of CheckPassword.
func (mr *MockUserRepositoryMockRecorder) CheckPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPassword", reflect.TypeOf((*MockUserRepository)(nil).CheckPassword), password)
}

// CreateAccount mocks base method.
func (m *MockUserRepository) CreateAccount(user model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockUserRepositoryMockRecorder) CreateAccount(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockUserRepository)(nil).CreateAccount), user)
}

// LockAccount mocks base method.
func (m *MockUserRepository) LockAccount(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockAccount", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockAccount indicates an expected call of LockAccount.
func (mr *MockUserRepositoryMockRecorder) LockAccount(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAccount", reflect.TypeOf((*MockUserRepository)(nil).LockAccount), id)
}

// RequestIpComputer mocks base method.
func (m *MockUserRepository) RequestIpComputer(ip model.Ip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestIpComputer", ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestIpComputer indicates an expected call of RequestIpComputer.
func (mr *MockUserRepositoryMockRecorder) RequestIpComputer(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestIpComputer", reflect.TypeOf((*MockUserRepository)(nil).RequestIpComputer), ip)
}

// UpdateProfile mocks base method.
func (m *MockUserRepository) UpdateProfile(id int, user model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserRepositoryMockRecorder) UpdateProfile(id, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserRepository)(nil).UpdateProfile), id, user)
}
