// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JieeiroSst/itjob/users/internal/delivery/http (interfaces: DeliveryHttp)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/JieeiroSst/itjob/model"
	gomock "github.com/golang/mock/gomock"
)

// MockDeliveryHttp is a mock of DeliveryHttp interface.
type MockDeliveryHttp struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryHttpMockRecorder
}

// MockDeliveryHttpMockRecorder is the mock recorder for MockDeliveryHttp.
type MockDeliveryHttpMockRecorder struct {
	mock *MockDeliveryHttp
}

// NewMockDeliveryHttp creates a new mock instance.
func NewMockDeliveryHttp(ctrl *gomock.Controller) *MockDeliveryHttp {
	mock := &MockDeliveryHttp{ctrl: ctrl}
	mock.recorder = &MockDeliveryHttpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryHttp) EXPECT() *MockDeliveryHttpMockRecorder {
	return m.recorder
}

// FindAllUser mocks base method.
func (m *MockDeliveryHttp) FindAllUser() (model.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllUser")
	ret0, _ := ret[0].(model.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllUser indicates an expected call of FindAllUser.
func (mr *MockDeliveryHttpMockRecorder) FindAllUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllUser", reflect.TypeOf((*MockDeliveryHttp)(nil).FindAllUser))
}

// LockAccount mocks base method.
func (m *MockDeliveryHttp) LockAccount(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockAccount", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockAccount indicates an expected call of LockAccount.
func (mr *MockDeliveryHttpMockRecorder) LockAccount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAccount", reflect.TypeOf((*MockDeliveryHttp)(nil).LockAccount), arg0)
}

// Login mocks base method.
func (m *MockDeliveryHttp) Login(arg0 model.Users) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockDeliveryHttpMockRecorder) Login(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockDeliveryHttp)(nil).Login), arg0)
}

// RequestIpComputer mocks base method.
func (m *MockDeliveryHttp) RequestIpComputer(arg0 model.Ip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestIpComputer", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestIpComputer indicates an expected call of RequestIpComputer.
func (mr *MockDeliveryHttpMockRecorder) RequestIpComputer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestIpComputer", reflect.TypeOf((*MockDeliveryHttp)(nil).RequestIpComputer), arg0)
}

// SignUp mocks base method.
func (m *MockDeliveryHttp) SignUp(arg0 model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockDeliveryHttpMockRecorder) SignUp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockDeliveryHttp)(nil).SignUp), arg0)
}

// UpdateProfile mocks base method.
func (m *MockDeliveryHttp) UpdateProfile(arg0 int, arg1 model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockDeliveryHttpMockRecorder) UpdateProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockDeliveryHttp)(nil).UpdateProfile), arg0, arg1)
}
