// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JieeiroSst/itjob/users/internal/http (interfaces: UserHttp)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/JieeiroSst/itjob/model"
	gomock "github.com/golang/mock/gomock"
)

// MockUserHttp is a mock of UserHttp interface.
type MockUserHttp struct {
	ctrl     *gomock.Controller
	recorder *MockUserHttpMockRecorder
}

// MockUserHttpMockRecorder is the mock recorder for MockUserHttp.
type MockUserHttpMockRecorder struct {
	mock *MockUserHttp
}

// NewMockUserHttp creates a new mock instance.
func NewMockUserHttp(ctrl *gomock.Controller) *MockUserHttp {
	mock := &MockUserHttp{ctrl: ctrl}
	mock.recorder = &MockUserHttpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserHttp) EXPECT() *MockUserHttpMockRecorder {
	return m.recorder
}

// FindAllUser mocks base method.
func (m *MockUserHttp) FindAllUser() (model.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllUser")
	ret0, _ := ret[0].(model.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllUser indicates an expected call of FindAllUser.
func (mr *MockUserHttpMockRecorder) FindAllUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllUser", reflect.TypeOf((*MockUserHttp)(nil).FindAllUser))
}

// LockAccount mocks base method.
func (m *MockUserHttp) LockAccount(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockAccount", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockAccount indicates an expected call of LockAccount.
func (mr *MockUserHttpMockRecorder) LockAccount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAccount", reflect.TypeOf((*MockUserHttp)(nil).LockAccount), arg0)
}

// Login mocks base method.
func (m *MockUserHttp) Login(arg0 model.Users) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockUserHttpMockRecorder) Login(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserHttp)(nil).Login), arg0)
}

// RequestIpComputer mocks base method.
func (m *MockUserHttp) RequestIpComputer(arg0 model.Ip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestIpComputer", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestIpComputer indicates an expected call of RequestIpComputer.
func (mr *MockUserHttpMockRecorder) RequestIpComputer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestIpComputer", reflect.TypeOf((*MockUserHttp)(nil).RequestIpComputer), arg0)
}

// SignUp mocks base method.
func (m *MockUserHttp) SignUp(arg0 model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockUserHttpMockRecorder) SignUp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockUserHttp)(nil).SignUp), arg0)
}

// UpdateProfile mocks base method.
func (m *MockUserHttp) UpdateProfile(arg0 int, arg1 model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserHttpMockRecorder) UpdateProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserHttp)(nil).UpdateProfile), arg0, arg1)
}
