// Code generated by MockGen. DO NOT EDIT.
// Source: http.go

// Package mock_http is a generated GoMock package.
package mock_http

import (
	reflect "reflect"

	model "github.com/JieeiroSst/itjob/model"
	gomock "github.com/golang/mock/gomock"
)

// MockUserHttp is a mock of UserHttp interface.
type MockUserHttp struct {
	ctrl     *gomock.Controller
	recorder *MockUserHttpMockRecorder
}

// MockUserHttpMockRecorder is the mock recorder for MockUserHttp.
type MockUserHttpMockRecorder struct {
	mock *MockUserHttp
}

// NewMockUserHttp creates a new mock instance.
func NewMockUserHttp(ctrl *gomock.Controller) *MockUserHttp {
	mock := &MockUserHttp{ctrl: ctrl}
	mock.recorder = &MockUserHttpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserHttp) EXPECT() *MockUserHttpMockRecorder {
	return m.recorder
}

// LockAccount mocks base method.
func (m *MockUserHttp) LockAccount(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockAccount", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockAccount indicates an expected call of LockAccount.
func (mr *MockUserHttpMockRecorder) LockAccount(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAccount", reflect.TypeOf((*MockUserHttp)(nil).LockAccount), id)
}

// Login mocks base method.
func (m *MockUserHttp) Login(user model.Users) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockUserHttpMockRecorder) Login(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserHttp)(nil).Login), user)
}

// RequestIpComputer mocks base method.
func (m *MockUserHttp) RequestIpComputer(ip model.Ip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestIpComputer", ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestIpComputer indicates an expected call of RequestIpComputer.
func (mr *MockUserHttpMockRecorder) RequestIpComputer(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestIpComputer", reflect.TypeOf((*MockUserHttp)(nil).RequestIpComputer), ip)
}

// SignUp mocks base method.
func (m *MockUserHttp) SignUp(user model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockUserHttpMockRecorder) SignUp(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockUserHttp)(nil).SignUp), user)
}

// UpdateProfile mocks base method.
func (m *MockUserHttp) UpdateProfile(id int, user model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserHttpMockRecorder) UpdateProfile(id, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserHttp)(nil).UpdateProfile), id, user)
}
