// Code generated by MockGen. DO NOT EDIT.
// Source: delivery_http.go

// Package mock_http is a generated GoMock package.
package mock_http

import (
	reflect "reflect"

	model "github.com/JieeiroSst/itjob/model"
	gomock "github.com/golang/mock/gomock"
)

// MockDeliveryHttp is a mock of DeliveryHttp interface.
type MockDeliveryHttp struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryHttpMockRecorder
}

// MockDeliveryHttpMockRecorder is the mock recorder for MockDeliveryHttp.
type MockDeliveryHttpMockRecorder struct {
	mock *MockDeliveryHttp
}

// NewMockDeliveryHttp creates a new mock instance.
func NewMockDeliveryHttp(ctrl *gomock.Controller) *MockDeliveryHttp {
	mock := &MockDeliveryHttp{ctrl: ctrl}
	mock.recorder = &MockDeliveryHttpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryHttp) EXPECT() *MockDeliveryHttpMockRecorder {
	return m.recorder
}

// LockAccount mocks base method.
func (m *MockDeliveryHttp) LockAccount(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockAccount", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockAccount indicates an expected call of LockAccount.
func (mr *MockDeliveryHttpMockRecorder) LockAccount(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAccount", reflect.TypeOf((*MockDeliveryHttp)(nil).LockAccount), id)
}

// Login mocks base method.
func (m *MockDeliveryHttp) Login(user model.Users) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockDeliveryHttpMockRecorder) Login(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockDeliveryHttp)(nil).Login), user)
}

// RequestIpComputer mocks base method.
func (m *MockDeliveryHttp) RequestIpComputer(ip model.Ip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestIpComputer", ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestIpComputer indicates an expected call of RequestIpComputer.
func (mr *MockDeliveryHttpMockRecorder) RequestIpComputer(ip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestIpComputer", reflect.TypeOf((*MockDeliveryHttp)(nil).RequestIpComputer), ip)
}

// SignUp mocks base method.
func (m *MockDeliveryHttp) SignUp(user model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockDeliveryHttpMockRecorder) SignUp(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockDeliveryHttp)(nil).SignUp), user)
}

// UpdateProfile mocks base method.
func (m *MockDeliveryHttp) UpdateProfile(id int, user model.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockDeliveryHttpMockRecorder) UpdateProfile(id, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockDeliveryHttp)(nil).UpdateProfile), id, user)
}
